### ISSUE TITLE
Cannot authenticate with valid credentials

### ISSUE THREAD

**Issue by stiakov** [joelmoniz/Git-Manager#9]
I'm getting this error using valid credentials.
Indeed I'm putting the url in the field every time that I try to Push to the remote repo.

> New repo created.
Snapshot complete
Pushing...
org.eclipse.jgit.api.errors.TransportException: https://github.com/stiakov/processing_sandbox.git: not authorized
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at git_manager.tool.GitOperations.pushToRemote(Unknown Source)
	at git_manager.tool.GitOptionToolbar$7.doInBackground(Unknown Source)
	at git_manager.tool.GitOptionToolbar$7.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/stiakov/processing_sandbox.git: not authorized
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:479)
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:398)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1173)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 9 more

**Comment by Moubassher** [comment]
I'm having this problem too. I overcame it by launching a batch file and forgot about JGit for now, but hating it.
